CREATE TABLE CONFIG_INFO
(
    ID           NUMBER(20,0) NOT NULL,
    DATA_ID      VARCHAR(255)  NOT NULL,
    GROUP_ID     VARCHAR(255),
    CONTENT      CLOB          NOT NULL,
    MD5          VARCHAR(32),
    GMT_CREATE   date DEFAULT SYSDATE NOT NULL,
    GMT_MODIFIED date DEFAULT SYSDATE NOT NULL,
    SRC_USER     CLOB,
    SRC_IP       VARCHAR(50)            DEFAULT NULL,
    APP_NAME     VARCHAR(128)           DEFAULT NULL,
    TENANT_ID    VARCHAR(128)           DEFAULT NULL,
    C_DESC       VARCHAR(256)           DEFAULT NULL,
    C_USE        VARCHAR(64)            DEFAULT NULL,
    EFFECT       VARCHAR(64)            DEFAULT NULL,
    TYPE         VARCHAR(64)            DEFAULT NULL,
    C_SCHEMA     CLOB,
    CONSTRAINT CONFIG_INFO_PK PRIMARY KEY (ID)
);

ALTER TABLE CONFIG_INFO
    ADD CONSTRAINT UK_CONFIGINFO_DATAGROUPTENANT UNIQUE (DATA_ID, GROUP_ID, TENANT_ID);



CREATE TABLE CONFIG_INFO_AGGR
(
    ID           NUMBER(20,0) NOT NULL,
    DATA_ID      VARCHAR(255)  NOT NULL,
    GROUP_ID     VARCHAR(255)  NOT NULL,
    DATUM_ID     VARCHAR(255)  NOT NULL,
    CONTENT      CLOB          NOT NULL,
    GMT_MODIFIED date DEFAULT SYSDATE NOT NULL,
    APP_NAME     VARCHAR(128)           DEFAULT NULL,
    TENANT_ID    VARCHAR(128),
    CONSTRAINT PK_CONFIG_INFO_AGGR PRIMARY KEY (ID)
);

ALTER TABLE CONFIG_INFO_AGGR
    ADD CONSTRAINT UK_CONFIGINFOAGGR_DGTD UNIQUE (DATA_ID, GROUP_ID, TENANT_ID, DATUM_ID);



CREATE TABLE CONFIG_INFO_BETA
(
    ID           NUMBER(20,0) NOT NULL,
    DATA_ID      VARCHAR(255)  NOT NULL,
    GROUP_ID     VARCHAR(128)  NOT NULL,
    APP_NAME     VARCHAR(128)           DEFAULT NULL,
    CONTENT      CLOB          NOT NULL,
    BETA_IPS     VARCHAR(1024)          DEFAULT NULL,
    MD5          VARCHAR(32)            DEFAULT NULL,
    GMT_CREATE   DATE DEFAULT SYSDATE NOT NULL,
    GMT_MODIFIED DATE DEFAULT SYSDATE NOT NULL,
    SRC_USER     CLOB,
    SRC_IP       VARCHAR(50)            DEFAULT NULL,
    TENANT_ID    VARCHAR(128),
    CONSTRAINT PK_CONFIG_INFO_BETA PRIMARY KEY (ID)
);

ALTER TABLE CONFIG_INFO_BETA
    ADD CONSTRAINT UK_CONFIGINFOBETA_DGT UNIQUE (DATA_ID, GROUP_ID, TENANT_ID);



CREATE TABLE CONFIG_INFO_TAG
(
    ID           NUMBER(20,0) NOT NULL,
    DATA_ID      VARCHAR(255)  NOT NULL,
    GROUP_ID     VARCHAR(128)  NOT NULL,
    TENANT_ID    VARCHAR(128),
    TAG_ID       VARCHAR(128)  NOT NULL,
    APP_NAME     VARCHAR(128)           DEFAULT NULL,
    CONTENT      CLOB          NOT NULL,
    MD5          VARCHAR(32),
    GMT_CREATE   DATE DEFAULT SYSDATE NOT NULL,
    GMT_MODIFIED DATE DEFAULT SYSDATE NOT NULL,
    SRC_USER     CLOB,
    SRC_IP       VARCHAR(50)            DEFAULT NULL,
    CONSTRAINT PK_CONFIG_INFO_TAG PRIMARY KEY (ID)
);
ALTER TABLE CONFIG_INFO_TAG
    ADD CONSTRAINT UK_CONFIGINFOTAG_DGT UNIQUE (DATA_ID, GROUP_ID, TAG_ID);



CREATE TABLE CONFIG_TAGS_RELATION
(
    ID        NUMBER(20,0) NOT NULL,
    TAG_NAME  VARCHAR(128)  NOT NULL,
    TAG_TYPE  VARCHAR(64) DEFAULT NULL,
    DATA_ID   VARCHAR(255)  NOT NULL,
    GROUP_ID  VARCHAR(128)  NOT NULL,
    TENANT_ID VARCHAR(128),
    NID       NUMBER(20,0) NOT NULL,
    CONSTRAINT PK_CONFIG_TAGS_RELATION PRIMARY KEY (ID, NID)
);
ALTER TABLE CONFIG_TAGS_RELATION
    ADD CONSTRAINT UK_CONFIGTAGRELATION_ITT UNIQUE (ID, TAG_NAME, TAG_TYPE);



CREATE TABLE GROUP_CAPACITY
(
    ID                NUMBER(20,0)  NOT NULL,
    GROUP_ID          VARCHAR(128)   NOT NULL,
    QUOTA             NUMBER(20,0) NOT NULL,
    USAGE             NUMBER(20,0) NOT NULL,
    MAX_SIZE          NUMBER(20,0) NOT NULL,
    MAX_AGGR_COUNT    NUMBER(20,0) NOT NULL,
    MAX_AGGR_SIZE     NUMBER(20,0) NOT NULL,
    MAX_HISTORY_COUNT NUMBER(20,0) NOT NULL,
    GMT_CREATE        DATE DEFAULT SYSDATE NOT NULL,
    GMT_MODIFIED      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_GROUP_CAPACITY PRIMARY KEY (ID)
);
ALTER TABLE GROUP_CAPACITY
    ADD CONSTRAINT UK_GROUP_ID UNIQUE (GROUP_ID);



CREATE TABLE HIS_CONFIG_INFO
(
    ID           NUMBER(20,0) NOT NULL,
    NID          NUMBER(20,0) NOT NULL,
    DATA_ID      VARCHAR(255)  NOT NULL,
    GROUP_ID     VARCHAR(128)  NOT NULL,
    APP_NAME     VARCHAR(128)           DEFAULT NULL,
    CONTENT      CLOB          NOT NULL,
    MD5          VARCHAR(32)            DEFAULT NULL,
    GMT_CREATE   DATE DEFAULT SYSDATE NOT NULL,
    GMT_MODIFIED DATE DEFAULT SYSDATE NOT NULL,
    SRC_USER     CLOB,
    SRC_IP       VARCHAR(50)            DEFAULT NULL,
    OP_TYPE      CHAR(10)               DEFAULT NULL,
    TENANT_ID    VARCHAR(128),
    CONSTRAINT PK_HIS_CONFIG_INFO PRIMARY KEY (ID, NID)
);


CREATE TABLE ROLES
(
    USERNAME VARCHAR(50) NOT NULL,
    ROLE     VARCHAR(50) NOT NULL
);


CREATE TABLE TENANT_CAPACITY
(
    ID                NUMBER(20,0)  NOT NULL,
    TENANT_ID         VARCHAR(128)   NOT NULL,
    QUOTA             NUMBER(20,0) NOT NULL,
    USAGE             NUMBER(20,0) NOT NULL,
    MAX_SIZE          NUMBER(20,0) NOT NULL,
    MAX_AGGR_COUNT    NUMBER(20,0) NOT NULL,
    MAX_AGGR_SIZE     NUMBER(20,0) NOT NULL,
    MAX_HISTORY_COUNT NUMBER(20,0) NOT NULL,
    GMT_CREATE        DATE DEFAULT SYSDATE NOT NULL,
    GMT_MODIFIED      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TENANT_CAPACITY PRIMARY KEY (ID)
);


ALTER TABLE TENANT_CAPACITY
    ADD CONSTRAINT UK_TENANT_ID UNIQUE (TENANT_ID);



CREATE TABLE TENANT_INFO
(
    ID            NUMBER(20,0) NOT NULL,
    KP            VARCHAR(128)  NOT NULL,
    TENANT_ID     VARCHAR(128),
    TENANT_NAME   VARCHAR(128),
    TENANT_DESC   VARCHAR(256) DEFAULT NULL,
    CREATE_SOURCE VARCHAR(32)  DEFAULT NULL,
    GMT_CREATE    NUMBER(20,0),
    GMT_MODIFIED  NUMBER(20,0),
    CONSTRAINT PK_TENANT_INFO PRIMARY KEY (ID)
);


ALTER TABLE TENANT_INFO
    ADD CONSTRAINT UK_TENANT_INFO_KPTENANTID UNIQUE (KP, TENANT_ID);


CREATE TABLE USERS
(
    USERNAME VARCHAR(50)  NOT NULL,
    PASSWORD VARCHAR(500) NOT NULL,
    ENABLED  char(1)      NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (USERNAME)
);

CREATE SEQUENCE SEQ_CONFIG_INFO
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    INCREMENT BY 1;



CREATE SEQUENCE SEQ_TENANT_INFO
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    INCREMENT BY 1;


CREATE SEQUENCE SEQ_HISTORY_CONFIG_INFO
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_CONFIG_INFO_BETA
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_CONFIG_INFO_TAG
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_CONFIG_INFO_AGGR
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE SEQ_CONFIG_TAGS_RELATION
    MINVALUE 1
    MAXVALUE 9999999999
    START WITH 1
    INCREMENT BY 1;


---PERMISSIONS这里RESOURCE为oracle的关键字，导致表无法创建，将RESOURCE改成RESOURCES
CREATE TABLE PERMISSIONS
(
    ROLE     VARCHAR(50)  NOT NULL,
    RESOURCES VARCHAR(255) NOT NULL,
    ACTION   VARCHAR(8)   NOT NULL
);


	
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', 1);

INSERT INTO ROLES (USERNAME, ROLE) VALUES ('nacos', 'ROLE_ADMIN');


